services:
  postgres:
    container_name: postgres_db
    restart: always
    image: 'postgres:latest'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'

volumes:
  postgres-data: